# Generated by Django 4.2 on 2023-06-08 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_customer_options_alter_customer_managers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='sex',
            field=models.CharField(choices=[('Male', 'm'), ('Female', 'f')], default='Male', max_length=10),
        ),
        migrations.AddField(
            model_name='customer',
            name='university',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
