# Generated by Django 4.2 on 2023-05-06 12:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_product_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
        migrations.RemoveField(
            model_name='product',
            name='thumbnail',
        ),
        migrations.AddField(
            model_name='product',
            name='dateinfo',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 6, 12, 1, 56, 699981)),
        ),
    ]
