# Generated by Django 4.2 on 2023-05-06 12:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_remove_product_image_remove_product_thumbnail_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='dateinfo',
            field=models.DateField(default=datetime.datetime(2023, 5, 6, 12, 2, 54, 367517)),
        ),
    ]
