# Generated by Django 4.2 on 2023-05-06 12:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_alter_product_dateinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='dateinfo',
            field=models.DateField(default=datetime.datetime(2023, 5, 6, 12, 3, 1, 480435)),
        ),
    ]
