# Generated by Django 4.2 on 2023-05-06 13:02

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_alter_product_dateinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan', models.CharField(choices=[('disabled', 'Disabled'), ('premium', 'Premium')], max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PlanDates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dates', models.DateField()),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('description', models.TextField(blank=True, null=True)),
                ('plan_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan_name', to='product.planname')),
            ],
        ),
        migrations.CreateModel(
            name='Month',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.IntegerField()),
                ('footer', models.TextField(blank=True, null=True)),
                ('plan_dates', models.ManyToManyField(related_name='plan_dates', to='product.plandates')),
            ],
        ),
    ]
