# Generated by Django 4.2 on 2023-05-06 13:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_planname_alter_product_dateinfo_plandates_month'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='dateinfo',
            field=models.DateField(default=datetime.datetime(2023, 5, 6, 13, 3, 15, 382181)),
        ),
    ]
