# Generated by Django 4.2 on 2023-05-06 13:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_alter_product_dateinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='month',
            name='plan_name',
            field=models.ManyToManyField(to='product.planname'),
        ),
        migrations.AlterField(
            model_name='product',
            name='dateinfo',
            field=models.DateField(default=datetime.datetime(2023, 5, 6, 13, 16, 1, 386945)),
        ),
    ]
