# Generated by Django 4.2 on 2023-05-11 12:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_alter_product_dateinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='dateinfo',
            field=models.DateField(default=datetime.datetime(2023, 5, 11, 12, 41, 19, 954070)),
        ),
    ]
