# Generated by Django 4.2 on 2023-06-11 22:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0003_customer_date_of_birth_customer_sex_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatSlack',
            fields=[
                ('channel_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.customer')),
            ],
        ),
        migrations.CreateModel(
            name='MessageSlack',
            fields=[
                ('ts', models.CharField(max_length=255, primary_key=True, serialize=False, verbose_name='message_id')),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='slack_bridge.chatslack')),
            ],
        ),
    ]
