# Generated by Django 4.2.2 on 2023-09-17 20:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatSlack',
            fields=[
                ('channel_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('message_id_info', models.CharField(max_length=255, null=True, unique=True, verbose_name='message_id')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.customer')),
            ],
        ),
        migrations.CreateModel(
            name='MessageSlackBridge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ts', models.CharField(max_length=255, unique=True, verbose_name='message_id')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('message_status', models.CharField(choices=[('C', 'completed'), ('S', 'sent'), ('D', 'delivered'), ('R', 'read'), ('U', 'uncompleted'), ('F', 'failed')], default='C', max_length=1)),
                ('wamid', models.TextField(null=True, verbose_name='whatsapp_message_id')),
                ('message_type', models.CharField(choices=[('M', 'marketing'), ('H', 'service')], default='H', max_length=1)),
                ('message_content', models.TextField(null=True, verbose_name='message_content')),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='slack_bridge.chatslack')),
            ],
        ),
    ]
