# Generated by Django 4.2 on 2023-06-11 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slack_bridge', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='messageslack',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
