# Generated by Django 4.2 on 2023-06-11 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slack_bridge', '0002_messageslack_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messageslack',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
