# Generated by Django 3.2 on 2023-06-13 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slack_bridge', '0003_alter_messageslack_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='messageslack',
            name='message_status',
            field=models.CharField(choices=[('C', 'completed'), ('S', 'sent'), ('D', 'delivered'), ('R', 'read')], default='C', max_length=1),
        ),
    ]
