# Generated by Django 3.2 on 2023-06-13 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slack_bridge', '0004_messageslack_message_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='messageslack',
            name='wamid',
            field=models.TextField(null=True, verbose_name='whatsapp_message_id'),
        ),
        migrations.AlterField(
            model_name='messageslack',
            name='message_status',
            field=models.CharField(choices=[('C', 'completed'), ('S', 'sent'), ('D', 'delivered'), ('R', 'read'), ('U', 'uncompleted'), ('F', 'failed')], default='C', max_length=1),
        ),
    ]
