# Generated by Django 3.2 on 2023-06-13 22:09

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('slack_bridge', '0005_auto_20230613_2144'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageSlackBridge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ts', models.CharField(max_length=255, unique=True, verbose_name='message_id')),
                ('created_at', models.DateTimeField(default=datetime.datetime(2023, 6, 14, 1, 9, 9, 815087))),
                ('message_status', models.CharField(choices=[('C', 'completed'), ('S', 'sent'), ('D', 'delivered'), ('R', 'read'), ('U', 'uncompleted'), ('F', 'failed')], default='C', max_length=1)),
                ('wamid', models.TextField(null=True, verbose_name='whatsapp_message_id')),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='slack_bridge.chatslack')),
            ],
        ),
        migrations.DeleteModel(
            name='MessageSlack',
        ),
    ]
