# Generated by Django 4.2.2 on 2023-06-16 00:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slack_bridge', '0006_auto_20230614_0109'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatslack',
            name='message_id_info',
            field=models.CharField(max_length=255, null=True, unique=True, verbose_name='message_id'),
        ),
        migrations.AddField(
            model_name='chatslack',
            name='message_info',
            field=models.TextField(null=True, verbose_name='message_info'),
        ),
        migrations.AddField(
            model_name='messageslackbridge',
            name='message_content',
            field=models.TextField(null=True, verbose_name='message_content'),
        ),
        migrations.AddField(
            model_name='messageslackbridge',
            name='message_type',
            field=models.CharField(choices=[('M', 'marketing'), ('H', 'service')], default='H', max_length=1),
        ),
        migrations.AlterField(
            model_name='messageslackbridge',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 16, 3, 37, 27, 566436)),
        ),
    ]
