# Generated by Django 4.2.2 on 2023-06-23 11:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slack_bridge', '0008_remove_chatslack_message_info_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messageslackbridge',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 23, 14, 10, 16, 5613)),
        ),
    ]
