# Generated by Django 4.2.2 on 2023-09-09 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slack_bridge', '0011_alter_messageslackbridge_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messageslackbridge',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
